<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <SpaRoot>..\printcetnrum_web.client</SpaRoot>
    <SpaProxyLaunchCommand>npm start</SpaProxyLaunchCommand>
    <SpaProxyServerUrl>https://localhost:4200</SpaProxyServerUrl>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>.</DockerfileContext>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Dockerfile" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="Dockerfile" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.10" />
    <PackageReference Include="Microsoft.AspNetCore.SpaProxy">
      <Version>8.*-*</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="8.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.TestPlatform" Version="17.13.0" />
    <PackageReference Include="Moq" Version="4.20.72" />
    <PackageReference Include="NETCore.MailKit" Version="2.1.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\printcetnrum_web.client\printcetnrum_web.client.esproj">
      <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
    </ProjectReference>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Context\" />
    <Folder Include="Migrations\" />
    <Folder Include="wwwroot\UserData\" />
  </ItemGroup>

  <ItemGroup>
    <_ContentIncludedByDefault Remove="wwwroot\UserData\prvyPou\1c266865-8258-45c2-9161-86e4644e070a.pdf" />
    <_ContentIncludedByDefault Remove="wwwroot\UserData\prvyPou\2a378c51-7323-4205-8a16-ff7a8414fd39.pdf" />
    <_ContentIncludedByDefault Remove="wwwroot\UserData\prvyPou\2bbcaf62-f856-41e9-bf16-5d17a9b5ddcf.pdf" />
    <_ContentIncludedByDefault Remove="wwwroot\UserData\prvyPou\8774ee55-4b37-42b0-abfd-e50a07f14838.xls" />
    <_ContentIncludedByDefault Remove="wwwroot\UserData\prvyPou\b19c365e-83e7-4c05-97ea-3e51b1213443.pdf" />
    <_ContentIncludedByDefault Remove="wwwroot\UserData\prvyPou\DesignFiles\Diploma_3c8826c9-ae97-4034-a4de-74f470c258c4.json" />
    <_ContentIncludedByDefault Remove="wwwroot\UserData\prvyPou\DesignFiles\Stamp_deb67abb-ca9d-49f3-837d-528ad0c882f6.json" />
    <_ContentIncludedByDefault Remove="wwwroot\UserData\prvyPou\DesignFiles\Stamp_e0444fd1-a08f-4b3a-ba88-c406f3872da1.json" />
    <_ContentIncludedByDefault Remove="wwwroot\UserData\prvyPou\Diplomas\e57cf388-4b0b-4204-bc0a-188f1085a959.json" />
  </ItemGroup>

</Project>
