version: '3.8'
services:
  client:
    build:
      context: ./printcetnrum_web.client
      dockerfile: Dockerfile
    ports:
      - "4200:4200"

  server:
    build:
      context: ./PrintCetnrum_Web.Server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
